### ISSUE TITLE
Running seeker 

### ISSUE THREAD

**Issue by simonbrahane** [thewhiteh4t/seeker#11]
Traceback (most recent call last):
  File "/usr/local/bin/seeker", line 209, in <module>
    ngrok()
  File "/usr/local/bin/seeker", line 82, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by thewhiteh4t** [comment]
nethunter?

**Comment by simonbrahane** [comment]
nope kali linux dualboot

**Comment by thewhiteh4t** [comment]
try this 
`cd seeker/Ngrok`
`./ngrok http 80`
it should run because you are using kali linux and this ngrok binary supports 64bit arch
also
ngrok binary in `seeker/termux/Ngrok`
should give the error you have posted above because the binary is for arm devices

**Comment by simonbrahane** [comment]
Thank you so much..it worked finally
