### ISSUE TITLE
New

### ISSUE THREAD

**Issue by mk-omg** [thewhiteh4t/seeker#117]
__
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
         \/      \/     \/      \/     \/

[>] Created By : thewhiteh4t
[>] Version    : 1.1.8
                                                      [+] Checking for Updates.....Traceback (most recent call last):
  File "seeker.py", line 310, in <module>
    ver_check()                                         File "seeker.py", line 49, in ver_check
    ver_rqst = requests.get(ver_url)
AttributeError: module 'requests' has no attribute 'get'

**Comment by thewhiteh4t** [comment]
@mk-omg please take a look at this and check
https://stackoverflow.com/questions/36522375/attributeerror-module-requests-has-no-attribute-get

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
