### ISSUE TITLE
Python code error

### ISSUE THREAD

**Issue by Falantovmailru** [thewhiteh4t/seeker#127]
Traceback (most recent call last):
  File "seeker.py", line 313, in <module>
    wait()
  File "seeker.py", line 145, in wait
    main()
  File "seeker.py", line 190, in main
    rqst = requests.get('http://free.ipwhois.io/json/{}'.format(var_ip))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='free.ipwhois.io', port=80): Max retries exceeded with url: /json/176.59.0.103 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb6b2566c>: Failed to establish a new connection: [Errno -2] Name or service not known'))
---What is this error? How to debug it? (sorry if i uncorrectly wrote?, i am russian and dont use translator!!!)

**Comment by thewhiteh4t** [comment]
are you able to visit this link http://free.ipwhois.io

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
