### ISSUE TITLE
error

### ISSUE THREAD

**Issue by diamonjack** [thewhiteh4t/seeker#142]
I found an error like this.

Traceback (most recent call last):
  File "seeker.py", line 337, in <module>
    template_select ()
  File "seeker.py", line 76, in template_select
    selected = int (input (G + '[>]' + W))
ValueError: invalid literal for int () with base 10: ''

**Comment by thewhiteh4t** [comment]
@diamonjack what did you enter?

**Comment by diamonjack** [comment]
sorry it turns out that I pressed enter too much, and it worked, but can I request a blank page and direct a link to a specific page to get location info

**Comment by thewhiteh4t** [comment]
@diamonjack please elaborate

**Comment by diamonjack** [comment]
for example I have got a link http: //****afc.ngrok.io/nearyou to send to someone
and after the link is accessed the person is immediately transferred to the facebok url or to another url after pressing the location access permission

**Comment by thewhiteh4t** [comment]
@diamonjack i am assuming you are trying gdrive template

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
