### ISSUE TITLE
Can't get URL

### ISSUE THREAD

**Issue by uwyeeu** [thewhiteh4t/seeker#193]
I am getting this error

[>] Created By : thewhiteh4t
[>] Version    : 1.2.4

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ UP ]

[+] Getting Serveo URL...

Traceback (most recent call last):
  File "seeker.py", line 351, in <module>
    tunnel_select()
  File "seeker.py", line 69, in tunnel_select
    serveo()
  File "seeker.py", line 132, in serveo
    proc = subp.Popen(['ssh', '-oStrictHostKeyChecking=no', '-R', '80:localhost:{}'.format(port), 'serveo.net'], stdout=tmpfile, stderr=tmpfile, stdin=subp.PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ssh'

**Comment by thewhiteh4t** [comment]
@uwyeeu install ssh
