### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by bit4lifeonline** [thewhiteh4t/seeker#20]
In Termux run seeker error...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/seeker", line 217, in <module>
    version()
  File "/data/data/com.termux/files/usr/bin/seeker", line 56, in version
    update = requests.get('https://raw.githubusercontent.com/thewhiteh4t/seeker/master/version.txt')
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /thewhiteh4t/seeker

**Comment by thewhiteh4t** [comment]
see the last line, how many times did you try?
either your internet is not working properly or its a github issue because i tested it and its working

**Comment by bit4lifeonline** [comment]
but it worked at kali linux,just Termux found this problem.

**Comment by thewhiteh4t** [comment]
its working in my termux, code is same. if possible can you try on a fresh termux, i.e. clear termux data

**Comment by bit4lifeonline** [comment]
Thank u very much!
and how can i change the default webpage of URL?

**Comment by thewhiteh4t** [comment]
you mean you want to use another template?

**Comment by bit4lifeonline** [comment]
yes,can i?

**Comment by thewhiteh4t** [comment]
yeah you can i have created different directories to make it easier just keep the variables same and add your own html and css, after that edit seeker.py and replace 'nearyou' with your new template folder name

**Comment by bit4lifeonline** [comment]
Oh,you r great!Thank u bro!

**Comment by thewhiteh4t** [comment]
All the best!!
