### ISSUE TITLE
new issue--solution please

### ISSUE THREAD

**Issue by viswatej44** [thewhiteh4t/seeker#212]
Error i got..

Traceback (most recent call last):
  File "seeker.py", line 365, in <module>
    tunnel_select()
  File "seeker.py", line 85, in tunnel_select
    serveo()
  File "seeker.py", line 150, in serveo
    with open('logs/serveo.txt', 'w') as tmpfile:
PermissionError: [Errno 13] Permission denied: 'logs/serveo.txt'

**Comment by thewhiteh4t** [comment]
@viswatej44 use `sudo`

**Comment by viswatej44** [comment]
@thewhiteh4t  even though running in 
kali@kali:~/seeker$ sudo python3 seeker.py -s whatsapp
[sudo] password for kali: 
[+] Checking Dependencies...

                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.2.5

[+] Checking for Updates.....[ Up-To-Date ]

[+] Checking Serveo Status...[ Online ]

[+] Getting Serveo URL...

its taking more time ..almost its been half an hour ..but im not able to get URL.

wish you could help

**Comment by thewhiteh4t** [comment]
@viswatej44 dont use serveo, they have changed lot of things and have removed ssl, so it cannot be used, I will remove it from seeker in next update, use manual mode till then, check DEMO section in readme and watch seeker v1.1.9 demo

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
