### ISSUE TITLE
Checking Servo status... and error

### ISSUE THREAD

**Issue by Raze4284** [thewhiteh4t/seeker#219]
When I enter the command python3 seeker.py everything goes fine, but when it comes to the stage Checking Servo status i got this:
File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket               
    cnx.do_handshake()                                                                                       
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1934, in do_handshake                           
    self._raise_ssl_error(self._ssl, result)                                                                 
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error                       
    raise WantReadError()                                                                                    
OpenSSL.SSL.WantReadError                                                                                    

During handling of the above exception, another exception occurred:                                          

Traceback (most recent call last):                                                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request                
    self._validate_conn(conn)                                                                                
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn               
    conn.connect()                                                                                           
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 361, in connect                          
    self.sock = ssl_wrap_socket(                                                                             
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket                   
    return context.wrap_socket(sock, server_hostname=server_hostname)                                        
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket               
    raise timeout("select timed out")                                                                        
socket.timeout: select timed out                                                                             

During handling of the above exception, another exception occurred:                                          

Traceback (most recent call last):                                                                           
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send                              
    resp = conn.urlopen(                                                                                     
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen                      
    retries = retries.increment(                                                                             
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 403, in increment                        
    raise six.reraise(type(error), error, _stacktrace)                                                       
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise                                         
    raise value                                                                                              
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen                      
    httplib_response = self._make_request(                                                                   
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request                
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seeker.py", line 365, in <module>
    tunnel_select()
  File "seeker.py", line 85, in tunnel_select
    serveo()
  File "seeker.py", line 134, in serveo
    rqst = requests.get('https://serveo.net', timeout=5)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

**Comment by Raze4284** [comment]
This error i got on termux too
