### ISSUE TITLE
Serveo Error

### ISSUE THREAD

**Issue by Yx-O** [thewhiteh4t/seeker#227]
[+] Checking Serveo Status...Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seeker.py", line 365, in <module>
    tunnel_select()
  File "seeker.py", line 85, in tunnel_select
    serveo()
  File "seeker.py", line 134, in serveo
    rqst = requests.get('https://serveo.net', timeout=5)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

**Comment by ChrysosKun** [comment]
I encountered the same error

**Comment by ChrysosKun** [comment]
[+] Checking Serveo Status...Traceback (most recent call last):                                    
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request    
    self._validate_conn(conn)                                                                      
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn   
    conn.connect()                                                                                 
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect              
    self.sock = ssl_wrap_socket(                                                                   
  File "/usr/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket       
    return context.wrap_socket(sock, server_hostname=server_hostname)                              
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket                                       
    return self.sslsocket_class._create(                                                           
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create                                          
    self.do_handshake()                                                                            
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake                                     
    self._sslobj.do_handshake()                                                                    
socket.timeout: _ssl.c:1107: The handshake operation timed out                                     

During handling of the above exception, another exception occurred:                                

Traceback (most recent call last):                                                                 
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send                  
    resp = conn.urlopen(                                                                           
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen          
    retries = retries.increment(                                                                   
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment            
    raise six.reraise(type(error), error, _stacktrace)                                             
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise            
    raise value                                                                                    
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen          
    httplib_response = self._make_request(                                                         
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request    
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)                                
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout   
    raise ReadTimeoutError(                                                                        
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seeker.py", line 365, in <module>
    tunnel_select()
  File "seeker.py", line 85, in tunnel_select
    serveo()
  File "seeker.py", line 134, in serveo
    rqst = requests.get('https://serveo.net', timeout=5)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='serveo.net', port=443): Read timed out. (read timeout=5)

**Comment by SCARLXRD-slep** [comment]
![Screenshot_20210202-090447.png](https://user-images.githubusercontent.com/65172703/106597838-bc320980-6535-11eb-9b90-7532ce31260d.png)

**Comment by MekoNix** [comment]
Use a command like this:python seeker.py -t manual
