### ISSUE TITLE
Traceback (most recent call last):   File "seeker.py", line 32, in <module>     import requests ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by loganwithdeadpool** [thewhiteh4t/seeker#234]
hey bro i tried everything but i am not abele to run seeker whenever i try to run seeker it says 
Traceback (most recent call last):
  File "seeker.py", line 32, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
please help me!
here is my install.log
[install.log](https://github.com/thewhiteh4t/seeker/files/5133925/install.log)

**Comment by thewhiteh4t** [comment]
@loganwithdeadpool in your install.log check line 227, the problem is right there

**Comment by thewhiteh4t** [comment]
`WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available`

dependencies are missing, refer to this https://stackoverflow.com/a/44758621

**Comment by thewhiteh4t** [comment]
closing due to inactivity.

**Comment by HkaDaYoungin** [comment]
got the same problem here litle bit late but yea

**Comment by Shammah1998** [comment]
I also noticed that when first opened it then closed it by mistake. Trying the second time, the error appeared. Turns out you need to set your terminal to sudo su then then the error will be solved. Worked in my case. Hope it helps

**Comment by Ns6677** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py",

**Comment by Ns6677** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py",
