### ISSUE TITLE
Not Running Error / seeker.py

### ISSUE THREAD

**Issue by 43r0ncyb3r** [thewhiteh4t/seeker#24]
Hi, i use seeker since 1.0.2 and now with the last update i found a bug, i installed everything and set the correct permission. I have to mention that i'm using Kali 4.17.

Output : 
                        __
  ______  ____   ____  |  | __  ____ _______
 /  ___/_/ __ \_/ __ \ |  |/ /_/ __ \\_  __ \
 \___ \ \  ___/\  ___/ |    < \  ___/ |  | \/
/____  > \___  >\___  >|__|_ \ \___  >|__|
	 \/      \/     \/      \/     \/        

[>] Created By : thewhiteh4t
[>] Version    : 1.0.6

[+] Checking Internet Connection... Working

[+] Checking For Seeker Updates... Up-to-date

[!] Loading Template...
Traceback (most recent call last):
  File "seeker.py", line 217, in <module>
    ngrok()
  File "seeker.py", line 83, in ngrok
    distutils.dir_util.copy_tree('{}/template/nearyou'.format(swd), tmp)
NameError: global name 'swd' is not defined

**Comment by thewhiteh4t** [comment]
Goto line number 80 i.e. 
```global api, site```
Change it to
```global api, site, swd```

**Comment by 43r0ncyb3r** [comment]
didn't work.. i still got `Traceback (most recent call last):
  File "seeker.py", line 217, in <module>
    ngrok()
  File "seeker.py", line 83, in ngrok
    distutils.dir_util.copy_tree('{}/template/nearyou'.format(swd), tmp)
NameError: name 'swd' is not defined
`

**Comment by thewhiteh4t** [comment]
yes, i was able to reproduce this error, please check if you are able to launch seeker by just typing seeker in console instead of ```python seeker.py```
You will get command not found, please execute ```install.sh``` again if that's the case as it will create the symlink for you

**Comment by thewhiteh4t** [comment]
pushed an update give it a go

**Comment by thewhiteh4t** [comment]
closing due to inactivity.

**Comment by 43r0ncyb3r** [comment]
working now, thank you

**Comment by 43r0ncyb3r** [comment]
I used the installer but there is no terminal shortcut, at least it working by `python seeker.py`. I use a shortcut to my .bashrc and now is working like a charm. thanks for such a great tool.

**Comment by thewhiteh4t** [comment]
Great, in recent update i have removed symlink, i will try to add in a future update.
