### ISSUE TITLE
thewhiteh4t/seeker

### ISSUE THREAD

**Issue by hamzaellatifi** [thewhiteh4t/seeker#26]
plese help me  ineed you 
traceback (most recent call last): 

Please reply to my message

**Comment by sasano1** [comment]
when i run seeker i got this massage
Traceback (most recent call last):
  File "seeker.py", line 203, in <module>
    network()
  File "seeker.py", line 42, in network
    requests.get('http://www.google.com/', timeout = 5)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=5)
how can i fix that
