### ISSUE TITLE
Can you explain why it's not working!

### ISSUE THREAD

**Issue by princethilak** [thewhiteh4t/seeker#30]
Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './Ngrok/ngrok'

This is what came when I put a command 
python seeker.py

**Comment by thewhiteh4t** [comment]
operating system?

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
