### ISSUE TITLE
keyError: 'continent'

### ISSUE THREAD

**Issue by josegaribay** [thewhiteh4t/seeker#305]
Key Error: 'continent'

Traceback (most recent call last):
  File "/opt/seeker/./seeker.py", line 368, in <module>
    wait()
  File "/opt/seeker/./seeker.py", line 199, in wait
    main()
  File "/opt/seeker/./seeker.py", line 250, in main
    var_continent = str(data['continent'])
KeyError: 'continent'

---

Hi Guys,
2 questions here.1 after serving this up on port: xyz and a local tunnel i get the following error when I enable location tracking from the (phone side) not sure why. 2nd question: is there a way to clear the cache on this program? I ask because when i start seeker in manual mode on any port i want it posts a previous device information also ending with that above traceback error. Im looking at the script but anything will help.

---

Im expecting to see the coordinates on seeker. I was able to launch the free.ipwhois.io/json/ on my mobile device and i do see latitude and longitude I also see the continent

---

**Please complete the following information :**
 
 - OS: Andriod
 - OS Version : Android 11
 - Browser : chrome
 - Full Browser Version 92.0.4515.131
 - Log files  
[Thu Aug 12 18:13:11 2021] PHP 7.4.21 Development Server (http://0.0.0.0:8080) started
[Thu Aug 12 18:13:14 2021] 127.0.0.1:33774 Accepted
[Thu Aug 12 18:13:14 2021] 127.0.0.1:33774 [200]: (null) /index.html
[Thu Aug 12 18:13:14 2021] 127.0.0.1:33774 Closing

**Comment by thewhiteh4t** [comment]
@josegaribay regarding the first question, the ipwhois api is called on your machine where you are running seeker and not on the device. I tested and I was not able to reproduce this error, something is blocking ipwhois on your end maybe?

for the second question it looks like there is some issue with the template files, which template did you try?

**Comment by josegaribay** [comment]
Oh ok thanks Ill look into the ipwhois more thoroughly on my machine.. as for the second question. I am using templete [0] NearYou

**Comment by thewhiteh4t** [comment]
@josegaribay for the cache issue try looking in the following path : 
```
seeker/template/nearyou/php
```
inside you will find 2 txt files : `info.txt` and `result.txt`
clear the file contents if there are any and launch seeker, I am implementing a much better approach at this, but there is some time in the release of that update
