### ISSUE TITLE
ngrok binary only for x86 64

### ISSUE THREAD

**Issue by KFDCompiled** [thewhiteh4t/seeker#31]
Anyone running this on an architecture besides x86 64 will need to download the appropriate file and replace the ngrok binary in Ngrok.

**Comment by thewhiteh4t** [comment]
i will be removing the binary in next update, ngrok will be downloaded via install script, i can check for architecture using ```uname -i```

**Comment by KFDCompiled** [comment]
👍

**Comment by ccrmj24** [comment]
hello I have a problem tells me to check line 205 that belongs to ngrok () another on line 77 like ngrok and utlimo is with subprocess.py on line 1047 that is the child executable

**Comment by thewhiteh4t** [comment]
Please copy paste the error here

**Comment by thewhiteh4t** [comment]
Install script updated.

**Comment by ccrmj24** [comment]
Hello this is the problem if i have :

Traceback (most recent call last):
  File "./seeker.py", line 205, in <module>
    ngrok()
  File "./seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE,
stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
@ccrmj24 i removed ngrok binary in last update, just execute `install.sh` and it will download the binary for you, then seeker should run without this error

**Comment by ccrmj24** [comment]
Traceback (most recent call last):
  File "./seeker.py", line 205, in <module>
    ngrok()
  File "./seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE,
stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
@ccrmj24 please share `install.log` file present in seeker directory

**Comment by ccrmj24** [comment]
ok .

.

**Comment by ccrmj24** [comment]
ok i send you the install.log

**Comment by Mrl008** [comment]
Im also facing same issue


Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
