### ISSUE TITLE
Code line issue 

### ISSUE THREAD

**Issue by asciiterminal** [thewhiteh4t/seeker#32]
Traceback (most recent call last):
  File "/usr/local/bin/seeker", line 205, in <module>
    ngrok()
  File "/usr/local/bin/seeker", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by asciiterminal** [comment]
i am using Kali linux latest version

**Comment by thewhiteh4t** [comment]
oh i just removed ngrok binary from the repo due to another issue, i have updated the install script to download ngrok binary like before so just run ```./install.sh``` and it will re download ngrok

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
