### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by bit4lifeonline** [thewhiteh4t/seeker#33]
kali
1.0.9

Checking For Seeker Updates...Traceback (most recent call last):
  File "/usr/local/bin/seeker", line 204, in <module>
    version()
  File "/usr/local/bin/seeker", line 51, in version
    update = requests.get('https://raw.githubusercontent.com/thewhiteh4t/seeker/master/version.txt', timeout = 5)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /thewhiteh4t/seeker/master/version.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e39132a90>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=5)'))

**Comment by thewhiteh4t** [comment]
is this happening everytime, also are you using a vpn?

**Comment by bit4lifeonline** [comment]
yes,when upgrade 1.0.9,i use vpn network.

**Comment by thewhiteh4t** [comment]
i guess its taking longer than 5 seconds try increasing the timeout value on line 51 
```timeout = 5```
try increasing it to 15

**Comment by bit4lifeonline** [comment]
same problem when i set to 25.
