### ISSUE TITLE
File "seeker.py", line 205, in <module>     ngrok()

### ISSUE THREAD

**Issue by danilogkir** [thewhiteh4t/seeker#36]
Hello... well, when i run it... it gives me this: 

```Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 75, in ngrok
    subp.Popen(['php', '-S', 'localhost:80', '-t', '{}/template/'.format(swd)], stderr=phplog, stdout=phplog)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php': 'php'
```

OS: Ubuntu 18.04

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by WyattAutomation** [comment]
I didn't have apache installed, fixed by running 
```
sudo apt install php libapache2-mod-php
```
Not sure if apache stuff is needed, but the above command resolved this issue for me.

**Comment by s403o** [comment]
> I didn't have apache installed, fixed by running
> 
> ```
> sudo apt install php libapache2-mod-php
> ```
> 
> Not sure if apache stuff is needed, but the above command resolved this issue for me.

Solved.
