### ISSUE TITLE
error when run seeker

### ISSUE THREAD

**Issue by sasano1** [thewhiteh4t/seeker#37]
Traceback (most recent call last):
  File "seeker.py", line 203, in <module>
    network()
  File "seeker.py", line 42, in network
    requests.get('http://www.google.com/', timeout = 5)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.google.com', port=80): Read timed out. (read timeout=5)

**Comment by thewhiteh4t** [comment]
are you from China?

**Comment by sasano1** [comment]
no im from iraq

> are you from China? @sasano1

no im from iraq

**Comment by sasano1** [comment]
> are you from China? @sasano1

can u help me or not

**Comment by sasano1** [comment]
Pls i need u help

**Comment by thewhiteh4t** [comment]
Okay i asked you this question because in China google is banned, so users from China have to use a VPN, I don't know about Iraq @sasano1

**Comment by sasano1** [comment]
did u mean this problem from internet

**Comment by thewhiteh4t** [comment]
are you able to browse www.google.com from your browser? @sasano1

**Comment by sasano1** [comment]
Yeb i can do that @thewhiteh4t
Do u have telegram i its be easy to contact with u

**Comment by thewhiteh4t** [comment]
I don't have telegram, i have discord

**Comment by sasano1** [comment]
Ok pls give me your discord id

**Comment by thewhiteh4t** [comment]
thewhiteh4t#3723
