### ISSUE TITLE
Please Help, Urgently.

### ISSUE THREAD

**Issue by moofshacks** [thewhiteh4t/seeker#375]
Whenever i choose the 'NearYou' template, and start ngrok, everything goes fine until you allow the location on the victims device, then i get this error message
----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1043, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7face3e2d2a0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipwhois.app', port=443): Max retries exceeded with url: /json/102.132.235.201 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7face3e2d2a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/seeker/seeker.py", line 335, in <module>
    wait()
  File "/home/kali/seeker/seeker.py", line 183, in wait
    data_parser()
  File "/home/kali/seeker/seeker.py", line 224, in data_parser
    rqst = requests.get(f'https://ipwhois.app/json/{var_ip}')
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipwhois.app', port=443): Max retries exceeded with url: /json/102.132.235.201 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7face3e2d2a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
------------------------------------------------------------------------------
Note that it only gives me the device information.

**Comment by thewhiteh4t** [comment]
@moofshacks I just tested and its working fine for me, can you test again ? If you still have the issue then its something on your end or your ISP

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
