### ISSUE TITLE
PHP Server...Traceback (most recent call last)

### ISSUE THREAD

**Issue by LendaMarian** [thewhiteh4t/seeker#377]
![Screenshot_2022-06-09-13-24-56-43_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/99845355/172826664-97abab10-c7be-4b1a-9300-d8beb864e935.jpg)

[+] Starting PHP Server...Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 334, in <module>
    SERVER_PROC = server()
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 149, in server
    proc = subp.Popen(cmd, stdout=phplog, stderr=phplog)
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1843, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'

**Comment by LendaMarian** [comment]
cat install.log
=====================
INSTALLING FOR TERMUX
=====================


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
python is already the newest version (3.10.5).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.

--------------------


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  fontconfig freetype giflib libgd libicu libjpeg-turbo libpng
  libresolv-wrapper libtiff libwebp libxslt libzip oniguruma tidy ttf-dejavu
  zstd
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libssh2.so in namespace (default)
E: Method https has died unexpectedly!
E: Sub-process https returned an error code (1)
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly

--------------------

Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.10/site-packages (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests) (2022.5.18.1)

--------------------

Requirement already satisfied: packaging in /data/data/com.termux/files/usr/lib/python3.10/site-packages (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from packaging) (3.0.9)

--------------------

=========
COMPLETED
=========

**Comment by LendaMarian** [comment]
pip install php
Requirement already satisfied: php in /data/data/com.termux/files/usr/lib/python3.10/site-packages (1.2.1)

**Comment by thewhiteh4t** [comment]
@LendaMarian php needs to be installed using the termux package manager i.e. `pkg` command and not via pip

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
