### ISSUE TITLE
seeker

### ISSUE THREAD

**Issue by Tamilspy** [thewhiteh4t/seeker#39]
Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 98, in ngrok
    geturl()
  File "seeker.py", line 83, in geturl
    r1 = requests.get('{}'.format(api))
  File "/root/requests/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/requests/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/requests/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/requests/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/requests/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3576d1bc90>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Tamilspy** [comment]
how to solve this error kali linux

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
