### ISSUE TITLE
Run error (Kali Linux)

### ISSUE THREAD

**Issue by msimon36** [thewhiteh4t/seeker#41]
I get this error upon execution:

[+] Starting Ngrok...

Traceback (most recent call last):
  File "seeker.py", line 205, in <module>
    ngrok()
  File "seeker.py", line 77, in ngrok
    subp.Popen(['./Ngrok/ngrok', 'http', '80'], stdin=subp.PIPE, stderr=subp.PIPE, stdout=subp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by LimerBoy** [comment]
chmod +x install.sh
sudo install.sh

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
