### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by zaidunz** [thewhiteh4t/seeker#422]
Starting PHP Server...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:8080/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zidan/seeker/seeker.py", line 341, in <module>
    SERVER_PROC = server()
  File "/home/zidan/seeker/seeker.py", line 162, in server
    php_rqst = requests.get(f'http://127.0.0.1:{port}/index.html')
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:8080/index.html

PLEASEE BRO HELP ME

**Comment by thewhiteh4t** [comment]
@zaidunz `pip3 install --upgrade urllib3`
