### ISSUE TITLE
[+] Starting PHP Server...Traceback (most recent call last):

### ISSUE THREAD

**Issue by BASHEER-A** [thewhiteh4t/seeker#427]
Hey how are you? I hope you're doing well. This is my problem when I try on macOS 

[+] Starting PHP Server...Traceback (most recent call last):
  File "/Users/admin/seeker/./seeker.py", line 341, in <module>
    SERVER_PROC = server()
                  ^^^^^^^^
  File "/Users/admin/seeker/./seeker.py", line 156, in server
    proc = subp.Popen(cmd, stdout=phplog, stderr=phplog)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
admin@Admins-MBP seeker %

**Comment by thewhiteh4t** [comment]
@BASHEER-A install php and this error should go away

**Comment by khanzode2abhi** [comment]
HOW CAN I SOLVE THIS ERROR.. PLEASE REPLY..

[+] Starting PHP Server...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
                                                      ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:8080/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abhi/Desktop/ABHI/seeker/seeker.py", line 341, in <module>
    SERVER_PROC = server()
                  ^^^^^^^^
  File "/home/abhi/Desktop/ABHI/seeker/seeker.py", line 162, in server
    php_rqst = requests.get(f'http://127.0.0.1:{port}/index.html')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:8080/index.html
