### ISSUE TITLE
i got error Failed to establish a new connection: [Errno -2] Name or service not known'))

### ISSUE THREAD

**Issue by MTGZ3R007** [thewhiteh4t/seeker#432]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/seeker/seeker.py", line 342, in <module>
    wait()
  File "/home/kali/seeker/seeker.py", line 190, in wait
    data_parser()
  File "/home/kali/seeker/seeker.py", line 231, in data_parser
    rqst = requests.get(f'https://ipwhois.app/json/{var_ip}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipwhois.app', port=443): Max retries exceeded with url: /json/2405:3800:8b8:9929:3c6a:d5eb:2c8c:275c (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffbdea5a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))

this error came out after victim click on the link given by me..i use cloudeflare and ngrok tunnels ,both got same error..pls help me sir

---

**To Reproduce**

Steps to reproduce the behavior, we cannot fix the issue if we can't reproduce it

---

**Expected behavior**

i expect i will get victim location 

---

**Screenshots**

i dont know ..sorry

---

**Please complete the following information :**
 
 - OS: kali linux 
 - OS Version [kali linux 2022.4]
 - Browser [chrome]
 - Full Browser Version []
 - Log files

**Comment by thewhiteh4t** [comment]
@MTGZ3R007 try to visit `https://ipwhois.app/json/` in your browser and check if its loading

**Comment by thewhiteh4t** [comment]
closing due to inactivity
