### ISSUE TITLE
ira keep giving me the same error  [Errno 2] No such file or directory , with google drive , whatsapp logo icon , and any linked source from my device

### ISSUE THREAD

**Issue by jupiter-root** [thewhiteh4t/seeker#434]
[+] Loading Google Drive Template...
[+] Enter GDrive File URL : file:///home/rooter/Desktop/seeker/template/gdrive/index.html
Traceback (most recent call last):
  File "/home/rooter/./Desktop/seeker/seeker.py", line 340, in <module>
    SITE = template_select(SITE)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rooter/./Desktop/seeker/seeker.py", line 142, in template_select
    importlib.import_module(f'template.{imp_file}')
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rooter/Desktop/seeker/template/mod_gdrive.py", line 9, in <module>
    with open('template/gdrive/js/location_temp.js', 'r') as js:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'template/gdrive/js/location_temp.js'

**Comment by thewhiteh4t** [comment]
@jupiter-root are you running tool from outside seeker directory ?

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
