### ISSUE TITLE
Outdated urllib3 error

### ISSUE THREAD

**Issue by khanzode2abhi** [thewhiteh4t/seeker#439]
HOW CAN I SOLVE THIS ERROR.. PLEASE REPLY..

[+] Starting PHP Server...Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/models.py", line 434, in prepare_url
scheme, auth, host, port, path, query, fragment = parse_url(url)
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 397, in parse_url
return six.raise_from(LocationParseError(source_url), None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:8080/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/abhi/Desktop/ABHI/seeker/seeker.py", line 341, in
SERVER_PROC = server()
^^^^^^^^
File "/home/abhi/Desktop/ABHI/seeker/seeker.py", line 162, in server
php_rqst = requests.get(f'[http://127.0.0.1:{port}/index.html](http://127.0.0.1:%7Bport%7D/index.html)')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 573, in request
prep = self.prepare_request(req)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 484, in prepare_request
p.prepare(
File "/usr/lib/python3/dist-packages/requests/models.py", line 368, in prepare
self.prepare_url(url, params)
File "/usr/lib/python3/dist-packages/requests/models.py", line 436, in prepare_url
raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:8080/index.html

**Comment by thewhiteh4t** [comment]
@khanzode2abhi what is your python version?

**Comment by khanzode2abhi** [comment]
My version of python is latest..
Python 3.11.2.

**Comment by thewhiteh4t** [comment]
@khanzode2abhi `pip3 install --upgrade urllib3` after this try seeker again
