### ISSUE TITLE
"no module named packaging" error

### ISSUE THREAD

**Issue by Mon0goescrazy** [thewhiteh4t/seeker#497]
When i type: python3 seeker.py this error comes out:
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 20, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by thewhiteh4t** [comment]
@TheNugget000 did you run install script before running the script ?

**Comment by Shittin** [comment]
I have the sam problem

**Comment by heiiwjww** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 20, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging' problem

**Comment by Ompatil999** [comment]
Unsubscribe

**Comment by thewhiteh4t** [comment]
https://docs.python.org/3/installing/index.html
