### ISSUE TITLE
where is the problem?

### ISSUE THREAD

**Issue by Moloooyy55544** [thewhiteh4t/seeker#520]
~/seeker $ python3 seeker.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/seeker/seeker.py", line 12, in <module>
    import utils
  File "/data/data/com.termux/files/home/seeker/utils.py", line 2, in <module>
    import requests
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
~/seeker $

**Comment by thewhiteh4t** [comment]
@Moloooyy55544 

https://stackoverflow.com/questions/66371458/modulenotfounderror-no-module-named-urllib3-packages-six
