### ISSUE TITLE
Error Running on Termux

### ISSUE THREAD

**Issue by Basudev1** [thewhiteh4t/seeker#55]
Got Run Time error on Termux with latest version of seeker

Got the below error
Traceback (most recent call last):
  File "seeker.py", line 202, in <module>
    serveo()
  File "seeker.py", line 84, in serveo
    proc = subp.Popen(['ssh', '-oStrictHostKeyChecking=no', '-R', '80:localhost:8080', 'serveo.net'], stdout = tmpfile, stderr = tmpfile, stdin = subp.PIPE)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
try `pkg install openssh`

**Comment by Basudev1** [comment]
it worked after installing openssh

Thank you
