### ISSUE TITLE
Cant start seeker.py 

### ISSUE THREAD

**Issue by Rootlente** [thewhiteh4t/seeker#61]
Traceback (most recent call last):
  File "./seeker.py", line 202, in <module>
    serveo()
  File "./seeker.py", line 80, in serveo
    subp.Popen(['php', '-S', '127.0.0.1:8080', '-t', '{}/template/'.format(swd)], stderr=phplog, stdout=phplog)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Rootlente** [comment]
i am using Ubuntu 4.15.0-47-generic

**Comment by thewhiteh4t** [comment]
@Rootlente follow these steps:
`cd seeker`
`ls`
you will see a `install.log` file
share it here

**Comment by Rootlente** [comment]
Reading package lists...
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (2.9.1)

**Comment by thewhiteh4t** [comment]
@Rootlente follow this
`su`
`cd seeker`
`chmod 777 install.sh`
`./install.sh`
after completing this again check `install.log` there should be no errors, then execute seeker

**Comment by Rootlente** [comment]
Traceback (most recent call last):
  File "./seeker.py", line 202, in <module>
    serveo()
  File "./seeker.py", line 80, in serveo
    subp.Popen(['php', '-S', '127.0.0.1:8080', '-t', '{}/template/'.format(swd)], stderr=phplog, stdout=phplog)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by thewhiteh4t** [comment]
php did not install properly, try manually executing :
`apt-get install php`
and share output

**Comment by robotmikhro** [comment]
Traceback (most recent call last):
  File "seeker.py", line 197, in <module>
    serveo()
  File "seeker.py", line 78, in serveo
    with open ('/tmp/serveo.txt', 'w') as tmpfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/serveo.txt'


Why

**Comment by thewhiteh4t** [comment]
@robotmikhro operating system?

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by bidinimous** [comment]
Hit:2 https://download.docker.com/linux/debian jessie InRelease
Hit:1 http://kali.download/kali kali-rolling InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.7.5-1).
python3-pip is already the newest version (18.1-5).
The following packages were automatically installed and are no longer required:
  libnfs12 libpotrace0 libtexlua52
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1479 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
php is already the newest version (2:7.3+69).
The following packages were automatically installed and are no longer required:
  libnfs12 libpotrace0 libtexlua52
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1479 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
ssh is already the newest version (1:8.0p1-7).
The following packages were automatically installed and are no longer required:
  libnfs12 libpotrace0 libtexlua52
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1479 not upgraded.
Requirement already satisfied: requests in /root/.local/lib/python3.7/site-packages (2.20.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.8.24)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.24.1)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)

**Comment by yasha-pixel** [comment]
Traceback (most recent call last):
  File "seeker.py", line 313, in <module>
    wait()
  File "seeker.py", line 145, in wait
    main()
  File "seeker.py", line 182, in main
    print(G + '[+]' + C + ' CPU Cores  : ' + W + var_cores)
TypeError: can only concatenate str (not "NoneType") to str
how to get rid of this error
