### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daniil2678** [thewhiteh4t/seeker#66]
why this error comes out and how to solve it:Traceback (most recent call last):
  File "seeker.py", line 174, in <module>
    serveo()
  File "seeker.py", line 56, in serveo
    with open ('/tmp/serveo.txt', 'w') as tmpfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/serveo.txt'

**Comment by vatsallemon** [comment]
I also get this error im from india

**Comment by thewhiteh4t** [comment]
@vatsallemon operating system?

**Comment by hipp0gryph** [comment]
> @vatsallemon operating system?
I have that error on Android system. In Russia serveo.net not work. Country block that site.

**Comment by hipp0gryph** [comment]
@thewhiteh4t Please, can you help me? I don't know what me do. I don't know Python and i not may change address server.

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.
